### ISSUE TITLE
Support for --modman-dir

### ISSUE THREAD

**Issue by pocallaghan** [colinmollenhour/modman#87] opened 2015-04-12 10:14 UTC
I've recently been reading a lot of articles about using .modman alongside composer to manage project dependencies. One thing that grates on me slightly is the fact that in these workflows the "vendor" modules sit in the same directory as the "project specific" code. This leaves you in a situation where you have committed code in the same directory as vendor code, which is not ideal. To draw a parallel this feels like having the src directory sitting in the vendor directory in a Symfony 2 project.

The only way I can think of getting around this would require modman supporting the ability to install from  (at least 2) different directories. This would allow project specific code to be committed / tracked in `.modman` and composer to deploy magento modules to `.modman-vendor` (or perhaps vice-versa as this may be simpler to achieve without modification to current tools such as `AOEpeople/composer-installers`). 

I'm thinking we could add a `--modman-dir` option, allowing the developer to optionally specify from which directory they wish to modman commands to operate. I've not thought about this in too much depth as I wanted to check your receptiveness to the idea first, however I believe implementation will largely be replacing any reference to `.modman` with a variable set at the top of the script. If the option is specified, current behaviour is completely unmodified, if it is, all commands are based against the specified directory.

**Comment by colinmollenhour** [comment] 2015-04-13 19:01
I'm certainly not opposed to the idea of allowing `.modman` to be user-specified although this seems to somewhat overlap with the `--basedir` option. To be honest I haven't kept up with the composer development so I'd have to defer to others' judgement such as yourself regarding the best way for modman and composer to get along. I know the Magento 2 folks have also been pondering a solution to this same issue.

**Comment by pocallaghan** [comment] 2015-04-13 21:16
I can't claim to be an expert when it comes to composer based solutions, I'm not currently using the approach in any production environments, but it's something that I've been trying to read up on. I initially thought `--basedir` would be a solution, but unless I'm misunderstanding something, it solves a slightly different problem.

 In brief:
`--basedir` - The ability to specify where to deploy code **to**. The main advantage being you can then keep `.modman` outside the Magento root.
`--modmandir` - The ability to specify where to deploy code **from**. The main advantage being you could deploy from more than one location.

As a general rule, any code pulled in as a dependency will be ignored by your VCS, with composer this is primarily the `vendor` directory. Given what appears to be [the standard approach](https://github.com/AOEpeople/Magento_SampleProject), one of the dependencies for a Magento project  will be a package of type `composer-installer` and will be designed to deal with Magento related packages (e.g. `aoepeople/composer-installers`). This will be placed in `vendor` along with any other "none Magento" dependencies. This package is an extension to composer and tells it to place code for packages of type `magento-source` directly into `htdocs` and packages of type `magento-module` into `.modman`. Logically therefore, both of these directories *should* be ignored by your VCS. Once all dependencies are fetched, a hook is triggered that will call `modman deploy-all` and thus make the site fully functional.

The project repo itself is inevitably going to have Magento related code developed specifically for this project, whether it be a custom module or theme. So where should this be tracked in the VCS? Currently from what I can tell you have two options:

 1. Just commit it in `.modman` and have both tracked and none tracked files in the same directory. There's no technical reason this doesn't work and is how the AOEPeople module works. I guess to a degree it could be considered more of a semantic thing, though it can get confusing and/or be a pain to set-up your VCS correctly.
 2. Make the project-specific code a dependency and commit into a separate repo, which ultimately ends up being inconvenient.

My solution is to simply keep "project code" and "dependency code" in different directories, thus maintaining the separation.
 
```bash
# deploy dependencies
modman deploy-all
# deploy in-house, project specific modules
modman deploy-all --modmandir .modman-local
```

**Comment by fbrnc** [comment] 2015-04-13 23:20
Hi @pocallaghan, Hi @colinmollenhour,

I really like the idea of adding the `--modmandir` parameter independently of the what the users are trying to to with it. And what you're trying to do with it sounds like a reasonable approach to me.

So If I understand you correctly you're planning on cloning your repo that already comes with a `.modman` directory and then run composer which would pull in the external modules and put them to something like `.modman-vendor`, right? Sounds like a very clean approach, but I'm wondering if you'd run into issues because of modman might be trying to cleanup the links from the other run with the different modmandir parameter (actually to be honest I don't know if modman ever tries to delete any symlinks). Another issue could be that it's easier to get confused by what file or directory comes from where and conflicts caused by overlapping directories and the execution order or the two modman runs and the order of the modules within each run might be harder to detect. Since this is something to watch out for in general I don't consider this to be a valid argument against this approach :)

While I really like this idea I never felt something was fundamentally wrong with having the "native" modules and the ones being pulled in via composer live in the same directory. Usually when I add something to the composer.json file I directly also add it to .gitignore and stop thinking about it. But I agree it would be a lot nicer to simply put the .modman-vendor directory to the .gitignore file and never even think about the origin of a module anymore since it's clear. 

Also there would be a much cleaner separation or project-specific modules (those would live in the .modman directory) and "shared modules" - which could be third-party modules or own modules that are generic enough so that the are reused in different project and that's why they're being pulled in via composer.

The more I think about this the more I think adding this complexity to the modman script and to the installer script is worth doing it.

Also you could use this mechanism to introduce different groups of modules like .modman-dev that only contains modules related to development or .modman-test for modules related to testing. Then of course we might want to teach the composer-installer to put a module somewhere else than in .modman-vendor and we might have to introduce .modman-dev and .modman-dev-vendor to keep the local modules separate from the composer ones. Ok, getting a little off-topic here, but I totally see a lot of potential in adding this simple parameter!

**Comment by fbrnc** [comment] 2015-04-13 23:24
@pocallaghan are you willing to implement this and do a pull request? I'm happy to help @colinmollenhour review and test this in case he's willing to add this feature...

**Comment by colinmollenhour** [comment] 2015-04-14 03:39
@pocallaghan It sounds like you like to have one repo with all code in it and just want there to be two separate modman folders in that repo? Is this accurate?

To me using @import is a good way to group lots of modules together. E.g. I can run "modman update core" and "modman update myproject" independently already or "modman update-all" to update everything. Example structure:

* .modman/
** core/
*** modman (@import Some_Module1, etc.. for each dependency)
*** Some_Module1/
*** Some_Module2/
** myproject/
*** modman (@import for submodules or just one big modman file for all links)
*** files or submodules

Personally I like to have the web root be a repo with .modman/ and all symlinks added to the gitignore file and then each module cloned under .modman as needed.

The thing is, there are so many way to organize it and everyone has their own way to do it or at least preferences. I'm generally open to adding features that are valuable and don't overlap other features so as this conversation develops I'm wondering why you don't just use @import. Having to specify the --modman-dir every time you run a command for that modman group doesn't seem very user-friendly..

All of that said, it does appear that composer is here to stay so I'd love to see a solution that lets modman and composer really work well together. E.g. if composer expects modules to be in /vendor perhaps one could simply create /vendor as a symlink to .modman?

**Comment by pocallaghan** [comment] 2015-04-16 20:05
@colinmollenhour hmm, interesting approach with the **@import**, the feature isn't something I've really played with. It's possible that I could achieve something like what I want using this sort of approach, however to achieve the same sort of thing I'd like, I'd need to write a composer-installer module that was capable of generating the modman file with the imports. Certainly a possibility. That being said I think that a `--modmandir` type could certainly offer a variety of possibilities as touched on by @fbrnc.

With that in mind I think I'll have a crack at implementing it when I get a bit of spare time. If I can get something up and running we could certainly play around with the possibilities, even if we decide ultimately that it's not something worth merging.

**Comment by fbrnc** [comment] 2015-04-16 22:07
Yesm I still think the `--modmandir` option is a great addition to modman. Even outside of the context of what you're trying to do here, but also especially for that. I can also totally see myself starting to separate external modules and project specific modules like this. 
I never used the @import feature, but it sounds like this would be mixing different "wiring" strategies and increasing the complexity of the project.
So, I'm all for this feature and I'll definitely will code review and test it.

**Comment by colinmollenhour** [comment] 2015-04-20 14:44
Yes, `@import` has been present since the very first version for exactly this purpose: grouping extensions together. Maybe there is some clever way to integrate modman and composer so that there is a "parent" project that has a modman file with an @import for each extension and a composer.json file which lists each extension as a dependency?

**Comment by razbakov** [comment] 2016-03-11 09:32
@pocallaghan is it finished? should we merge it?

**Comment by cags** [comment] 2016-03-11 10:14
@razbakov We've been using my fork in production along with composer for a bunch of our clients. We have a simple script in our tools folder that runs the composer install followed by modman deploy with our custom path. This allows us to force replace files with local modules if require and enables us to keep code in the project repo (private/custom modules) separate from dependencies. So it's definitely usable.

Merging into core is up to @colinmollenhour. I get the impression that ultimately he wasn't convinced it was the best approach / in-line with his vision of the tool.

**Comment by razbakov** [comment] 2016-03-11 11:28
@colinmollenhour original .modman directory is sometimes hidden and it is not very usable, that's why we name it `features` in our company and create symlink `.modman -> features`. It would be way better to have source and target dirs configurable. Please merge this PR. Thank you and looking forward.

**Comment by colinmollenhour** [comment] 2016-03-11 20:40
Hey guys. Sorry for leaving you hanging on this issue. The pull request is very clean so I am ok to accept it as implemented. However, there are merge conflicts and I don't have time to spend on it so if someone wants to submit a new PR or update the existing one I will merge it. -Thanks!

**Comment by pocallaghan** [comment] 2016-03-11 21:24
I've rebased my pull request. Only did some rudimentary checks, but the only thing that threw a merge conflect was the descriptions.

**Comment by colinmollenhour** [comment] 2016-03-11 21:27
Thanks. Merged #90

**Closed by colinmollenhour** 2016-03-11 21:27 UTC

**Comment by razbakov** [comment] 2016-03-14 09:46
it looks for `.modman` directory, but it should check modmandir from parameter

```
> vendor/bin/modman deploy-all --force --modmandir features --basedir src
Module Manager directory not found.
Run "modman init" in the root of the project with which you would like to use Module Manager.
Script vendor/bin/modman deploy-all --force --modmandir features --basedir src handling the post-update-cmd event returned with an error


  [RuntimeException]
  Error Output:
```

**Comment by razbakov** [comment] 2016-03-14 09:52
deploy-all doesn't work:

```
> vendor/bin/modman deploy-all --force --modmandir features --basedir src
Too many arguments to deploy-all command.
Script vendor/bin/modman deploy-all --force --modmandir features --basedir src handling the post-update-cmd event returned with an error


  [RuntimeException]
  Error Output:
```
